//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_SoundForest : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabCylinder
        {
            get
            {
                return SteamVR_Actions.soundForest_GrabCylinder;
            }
        }
        
        public virtual SteamVR_Action_Boolean PluckCylinder
        {
            get
            {
                return SteamVR_Actions.soundForest_PluckCylinder;
            }
        }
        
        public virtual SteamVR_Action_Boolean CreateMenu
        {
            get
            {
                return SteamVR_Actions.soundForest_CreateMenu;
            }
        }
        
        public virtual SteamVR_Action_Boolean ColorMenu
        {
            get
            {
                return SteamVR_Actions.soundForest_ColorMenu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 SnapTurn
        {
            get
            {
                return SteamVR_Actions.soundForest_SnapTurn;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.soundForest_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticLeft
        {
            get
            {
                return SteamVR_Actions.soundForest_HapticLeft;
            }
        }
        
        public virtual SteamVR_Action_Vibration HapticRight
        {
            get
            {
                return SteamVR_Actions.soundForest_HapticRight;
            }
        }
    }
}
